### ISSUE TITLE
unknown map after open to .db or osu! collection from save files (1.0.197) 

### ISSUE THREAD

**Issue by JergenRoss** [Piotrekol/CollectionManager#53] opened 2022-02-23 22:45 UTC
try click `save > .db or osu! collection` then click `open to .db or load osu! collection`, you see some unknown map.

use .osdb for work only.

example: open load to `.osdb`
![image](https://user-images.githubusercontent.com/59808813/155421348-a20969ff-59dd-4477-b8ca-7924ece6fe6c.png)

problems: open load to `.db` or `osu collection`
![image](https://user-images.githubusercontent.com/59808813/155421971-732008fb-d899-44a5-900a-31e2453d49e0.png)

**Comment by Kuuuube** [comment] 2022-02-23 22:49
This is not a bug nor is it something that can be fixed by CM. That is just how osu! handles its collection.db files.
https://github.com/Piotrekol/CollectionManager#collection-file-formats

**Closed** 2022-02-23 22:52 UTC
