### ISSUE TITLE
Can't download missing beatmaps (no option to enter file director or cookies)

### ISSUE THREAD

**Issue by SNMercy** [Piotrekol/CollectionManager#49] opened 2022-01-31 22:33 UTC
I can't seem to download the missing beatmaps and this error message keeps popping up.  I don't get any prompt to choose a file destination or enter the cookies. This occurs right when I click on "Download all missing beatmaps"

System.NotImplementedException: download sources configuration is missing!
   at App.OsuDownloadManager.<>c.<.ctor>b__50_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   at App.SidePanelActionsHandler.DownloadAllMissing(Object sender, Object data)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Piotrekol** [comment] 2022-02-01 19:19
duplicate of #45

**Closed by Piotrekol** 2022-02-01 19:19 UTC
Labels: duplicate
